apiVersion: v1
kind: Service
metadata:
  name: strimzi-prometheus
  namespace: infra-prometheus
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    app.kubernetes.io/instance: strimzi-prometheus
    prometheus: strimzi-prometheus
  type: ClusterIP
